name: 'Eggdrop Docker development testing'

on:
  push:
    workflow_dispatch:
    branches:
    - master
    - tests
#  pull_request:
#    branches: [ $default-branch ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: cd develop
    - run: pwd
    - run: echo 'putlog "[userlist]"; putlog "[passwdok user -]"; putlog [channels]; putlog "$botnick"; putlog "[server list]"; putlog "[dcclist]"; die' >> docker.tcl
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eggdrop:$(date +%s)
